### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by konstantinosKokos** [konstantinosKokos/aethel#7]
- [x] refine modifiers to account for internal hidden structure
- [x] modifiers over intermediate nodes do not get function types (5)
- [x] majority voting no longer correct
- [x] meta-type for polymorphic conjuction (*)
- [x] filter by argument to make sense of promotion
- [x] collapsing permutations post-extraction
- [x] cp
- [x] mwu lexical entries (more/than etc)
- [x] vnw: det -> (np: su -> ssub) : body -> whrel (wiens/welk/etc.)
- [x] inventorize coordination (treat on lexical level)
- [x] coordination non-polymorphic
- [x] prioritize between coordinators
- [x] head/funcwords distinction for determiner
- [x] search utilities
- [x] decorate lexicons with file id for backwards checking
- [x] remove everything unrelated to type extraction
- [ ] lassy large
- [x] post-extraction viz 
- [x] noun/noun-phrase distinction
- [x] documentation, gradual typing, overall code sanity
- [x] modifiers
- [x] ignore secomdary heads but only in the case of gap
- [x] Remove intermediate nodes and check for new errors
- [x] Coordinator type assignment
- [x] Extend type system to additives (!)
- [x] Assign multiple types to a word with extended system
- [x] Refactor the supertagger
--
- [x] chart parsing or any sort of proof search
